name: Build Native Minecraft Server

on:
  push:
    branches:
      - main
    tags:
      - 'v-*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 下载 GraalVM 企业版
      - name: Download GraalVM Enterprise Edition
        run: |
          wget --no-check-certificate -O graalvm-ee.tar.gz "https://download.oracle.com/otn/utilities_drivers/oracle-labs/graalvm-ee-java17-linux-amd64-21.3.13.tar.gz?AuthParam=1743956974_3420b8b65c314b11256c2a6d30b91b51"

      # 解压 GraalVM 压缩包
      - name: Extract GraalVM Enterprise Edition
        run: |
          tar -zxvf graalvm-ee.tar.gz

      # 配置环境变量
      - name: Setup GraalVM Environment
        run: |
          echo "GRAALVM_HOME=$(pwd)/graalvm-ee-java17-21.3.13" >> $GITHUB_ENV
          echo "$(pwd)/graalvm-ee-java17-21.3.13/bin" >> $GITHUB_PATH
          echo "GRAAL_EE_DOWNLOAD_TOKEN=${{ secrets.GRAAL_EE_DOWNLOAD_TOKEN }}" >> $GITHUB_ENV


      # 后续步骤保持不变，例如构建、测试和打包
      - name: Check build.sh
        shell: bash
        run: shellcheck build.sh

      - name: Build and run native Minecraft server
        shell: bash
        run: |
          ./build.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-server
          path: ./native-minecraft-server

      # Extract the tag name if we're running from a tag trigger
      - name: Set tag name from ref
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Create a zip file for the release
      - name: Zip artifact for release
        run: zip -r minecraft-server.zip .
        if: env.TAG_NAME != ''

      # Create a release using the tag
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: env.TAG_NAME != ''
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: minecraft-server.zip
          token: ${{ secrets.GITHUB_TOKEN }}
