name: Build Native Minecraft Server

on:
  push:
    branches:
      - main
    tags:
      - 'v-*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}


      # 后续步骤保持不变，例如构建、测试和打包
      - name: Check build.sh
        shell: bash
        run: shellcheck build.sh

      - name: Build and run native Minecraft server
        shell: bash
        run: |
          ./build.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-server
          path: .

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      # 下载所有构建产物到 artifacts 目录
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # 对每个构建产物单独打包成 zip 文件
      - name: Zip individual build artifacts for release
        run: |
          for dir in artifacts/*; do
            if [ -d "$dir" ]; then
              zip -r "${dir}.zip" "$dir"
            fi
          done

      # 设置日期用于 release tag（格式为 YYYY.MM.DD）
      - name: Set up date
        id: date
        run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      # 创建 release，并上传所有单独打包好的 zip 文件
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.DATE }}
          name: Release v${{ env.DATE }}
          draft: false
          prerelease: false
          files: artifacts/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
